version: 0.2
phases:
  build:
    commands:
    - mvn clean install
  post_build:
    commands:
    - mv target/ci-cd-proj-0.0.1-SNAPSHOT.jar ci-cd-proj-0.0.1-SNAPSHOT.jar
artifacts:
  files:
  - ci-cd-proj-0.0.1-SNAPSHOT.jar