version: 0.2
phases:
  build:
    commands:
    - mvn clean install
  post_build:
    commands:
    - mv target/magic-demo-0.0.1-SNAPSHOT.jar magic-demo-0.0.1-SNAPSHOT.jar
artifacts:
  files:
  - magic-demo-0.0.1-SNAPSHOT.jar